// =============================================================================
// THE SHARED DESIGN TOKENS. One palette, two products.
// =============================================================================
// This file is part of `uikit/`, which is BYTE-IDENTICAL in every tool that
// uses it (see README.md). Nothing app-specific belongs here: a product's name,
// mark and favicon live in its own `src/brand.ts`, outside this folder, which
// is why the folder can be copied wholesale between repositories.
//
// One config drives three layers so they cannot drift apart:
//   1. CSS custom properties (:root / [data-theme="dark"]) - generated by
//      renderRootCss() and inlined into <head> by vitePluginBrand.ts, so there
//      is no flash of the wrong theme.
//   2. Ant Design tokens - antd.ts reads this file instead of hardcoding.
//   3. The uikit's own stylesheets and primitives, which name only variables.
//
// Keep this file dependency-free: it is imported by both the browser bundle and
// the Node-side Vite plugin.
// -----------------------------------------------------------------------------

/** A full set of themeable colors for one mode (light or dark). */
export interface Palette {
  // Primary (brand) and its variants
  brand: string;
  brandStrong: string; // hover / pressed brand
  brandSoft: string; // tinted fill behind selected/brand surfaces
  brandBorder: string;
  // Secondary accent. Defaults to brandStrong so it is inert until you set it;
  // exposed as var(--secondary) for your own accents.
  secondary: string;
  // Sidebar / navigation rail. `navBg` is a MATERIAL: a translucent fill the
  // page shows faintly through, so give it an alpha and let `components.css`
  // put the blur behind it.
  navBg: string;
  navBgHover: string;
  navBgActive: string;
  navFg: string;
  /** Type that has to hold its own on the navigation - the product's name, the
   *  signed-in person - as opposed to an item's quieter label. It is a separate
   *  token because the navigation is a light material in light mode and a dark
   *  one in dark mode: "white" was correct for exactly one of those. */
  navFgStrong: string;
  navFgActive: string;
  navBorder: string;
  // Surfaces: canvas (page) < surface (content) < surface2 (raised or sunken
  // well - the same value serves both, because a recessed panel and a raised
  // one differ by their shadow, not by their fill)
  canvas: string;
  surface: string;
  surface2: string;
  border: string;
  borderStrong: string;
  illSurface: string; // "paper" fill inside the state illustrations
  // Text
  text: string;
  text2: string;
  text3: string;
  // Semantic status triples (foreground / pastel background / border)
  ok: string; okBg: string; okBd: string;
  pending: string; pendingBg: string; pendingBd: string;
  review: string; reviewBg: string; reviewBd: string;
  danger: string; dangerBg: string; dangerBd: string;
  // The "you are here" wash: a highlighter over the thing a link led to. It is
  // not a status - nothing is wrong or pending about a value somebody asked to
  // be shown - so it gets its own colour rather than borrowing one that means
  // something.
  markBg: string; markBd: string;
  // Provenance (base = inherited from a shared layer, inherit = neutral)
  base: string; baseBg: string; baseBd: string;
  inherit: string; inheritBg: string; inheritBd: string;
  // Severity, and the surface each severity dot sits on. A FIVE-step scale
  // rather than the four semantic tones, because "unknown" is a real answer
  // that must not read as "none": a package nobody has scanned is not a clean
  // one. COLOUR IS NEVER THE ONLY SIGNAL - every severity is also a word and a
  // dot whose fill differs - so these survive greyscale and colour blindness.
  sevCritical: string; sevHigh: string; sevMedium: string; sevLow: string; sevUnknown: string;
  sevCriticalBg: string; sevHighBg: string; sevMediumBg: string; sevLowBg: string; sevUnknownBg: string;
  // The verdict of a comparison. `inconclusive` is deliberately not a grey that
  // reads as "nothing happened": it is a state with an action in it (go and
  // look at the rest), and looking like an empty result is how it gets ignored.
  vBetter: string; vWorse: string; vUnchanged: string; vInconclusive: string;
}

/** The palette-and-metrics half of a theme. Identity lives in brand.ts. */
export interface ThemeTokens {
  /** Shape tokens fed to Ant Design. */
  shape: { borderRadius: number; controlHeight: number };
  /** Type tokens fed to Ant Design. */
  type: { fontFamily: string; monoFamily: string; fontSizeBase: number };
  light: Palette;
  dark: Palette;
  /** Environment identity colors (which environment an instance runs in). */
  envColors: Record<string, string>;
}

// Palette key -> CSS custom property. Every stylesheet and every primitive in
// this kit names one of these and never a hex, which is what makes a rebrand
// one edit instead of a search.
export const VAR_MAP: Array<[keyof Palette, string]> = [
  ["brand", "--brand"], ["brandStrong", "--brand-strong"], ["brandSoft", "--brand-soft"],
  ["brandBorder", "--brand-border"], ["secondary", "--secondary"],
  ["navBg", "--nav-bg"], ["navBgHover", "--nav-bg-hover"], ["navBgActive", "--nav-bg-active"],
  ["navFg", "--nav-fg"], ["navFgStrong", "--nav-fg-strong"],
  ["navFgActive", "--nav-fg-active"], ["navBorder", "--nav-border"],
  ["canvas", "--canvas"], ["surface", "--surface"], ["surface2", "--surface-2"],
  ["border", "--border"], ["borderStrong", "--border-strong"], ["illSurface", "--ill-surface"],
  ["text", "--text"], ["text2", "--text-2"], ["text3", "--text-3"],
  ["ok", "--c-ok"], ["okBg", "--c-ok-bg"], ["okBd", "--c-ok-bd"],
  ["pending", "--c-pending"], ["pendingBg", "--c-pending-bg"], ["pendingBd", "--c-pending-bd"],
  ["review", "--c-review"], ["reviewBg", "--c-review-bg"], ["reviewBd", "--c-review-bd"],
  ["danger", "--c-danger"], ["dangerBg", "--c-danger-bg"], ["dangerBd", "--c-danger-bd"],
  ["markBg", "--c-mark-bg"], ["markBd", "--c-mark-bd"],
  ["base", "--c-base"], ["baseBg", "--c-base-bg"], ["baseBd", "--c-base-bd"],
  ["inherit", "--c-inherit"], ["inheritBg", "--c-inherit-bg"], ["inheritBd", "--c-inherit-bd"],
  ["sevCritical", "--sev-critical"], ["sevHigh", "--sev-high"], ["sevMedium", "--sev-medium"],
  ["sevLow", "--sev-low"], ["sevUnknown", "--sev-unknown"],
  ["sevCriticalBg", "--sev-critical-bg"], ["sevHighBg", "--sev-high-bg"],
  ["sevMediumBg", "--sev-medium-bg"], ["sevLowBg", "--sev-low-bg"],
  ["sevUnknownBg", "--sev-unknown-bg"],
  ["vBetter", "--v-better"], ["vWorse", "--v-worse"], ["vUnchanged", "--v-unchanged"],
  ["vInconclusive", "--v-inconclusive"],
];

// -----------------------------------------------------------------------------
// Defaults: the identity these tools ship with. Change values via a PRESET
// below rather than editing these, so the baseline is always there to diff
// against - and so both products move together when one of them moves.
//
// THE PALETTE IS APPLE'S SYSTEM PALETTE, and deliberately so: these two tools
// are meant to read as one suite built for the platform their operators
// actually sit in front of. That means the neutrals apple.com uses (#1d1d1f
// type, #f5f5f7 grounds, #d2d2d7 rules) rather than a generic blue-grey ramp,
// and the system accents (systemBlue, systemGreen, systemOrange, systemRed,
// systemIndigo) rather than colours picked one at a time.
//
// The single biggest consequence is the NAVIGATION. It used to be a slab of
// navy, which is the house style of every enterprise dashboard and belongs to
// none of them. It is now a MATERIAL: a translucent neutral the page shows
// faintly through, dark type on it, and one brand-filled pill for where you
// are - a Finder sidebar, not a chrome band. The blur that makes it a material
// lives in components.css; the alpha that lets it work lives here.
// -----------------------------------------------------------------------------
export const defaultTokens: ThemeTokens = {
  // 8 and 32: a control the size of a macOS push button, with the continuous
  // corner the whole platform rounds to. 6/30 read as a web form.
  shape: { borderRadius: 8, controlHeight: 32 },
  type: {
    // San Francisco first, by its real names as well as through -apple-system,
    // so the face is right on a Mac and on an iPad viewing the same page. Inter
    // is the closest widely-installed stand-in and sits ahead of the platform
    // defaults for everyone else.
    fontFamily:
      `-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", Inter, "Segoe UI Variable Text", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif`,
    // ui-monospace resolves to SF Mono on Apple platforms, which is the point.
    monoFamily:
      `ui-monospace, "SF Mono", SFMono-Regular, "JetBrains Mono", Menlo, Consolas, "Liberation Mono", monospace`,
    fontSizeBase: 13,
  },
  light: {
    brand: "#0071e3", brandStrong: "#0058b9", brandSoft: "#e8f1fd", brandBorder: "#a8cbf4",
    // systemIndigo, for an accent that is genuinely a second voice rather than
    // the brand at another lightness.
    secondary: "#5856d6",
    navBg: "rgba(246, 246, 248, 0.72)", navBgHover: "rgba(0, 0, 0, 0.05)", navBgActive: "#0071e3",
    navFg: "#4b4b50", navFgStrong: "#1d1d1f", navFgActive: "#ffffff",
    navBorder: "rgba(0, 0, 0, 0.09)",
    canvas: "#f0f0f3", surface: "#ffffff", surface2: "#f6f6f8",
    border: "#e4e4e7", borderStrong: "#d2d2d7", illSurface: "#ffffff",
    text: "#1d1d1f", text2: "#6e6e73", text3: "#96969b",
    markBg: "#fff6d6", markBd: "#ffd426",
    ok: "#1b7f3b", okBg: "#e9f7ed", okBd: "#bde5c9",
    pending: "#b25000", pendingBg: "#fff3e5", pendingBd: "#ffd9ac",
    review: "#0071e3", reviewBg: "#e8f1fd", reviewBd: "#a8cbf4",
    danger: "#d70015", dangerBg: "#ffebe9", dangerBd: "#ffc7c2",
    base: "#5856d6", baseBg: "#efeffd", baseBd: "#cfcff7",
    inherit: "#6e6e73", inheritBg: "#f2f2f5", inheritBd: "#e4e4e7",
    sevCritical: "#c1262e", sevHigh: "#b85c0a", sevMedium: "#8f6c00",
    sevLow: "#1b7f3b", sevUnknown: "#86868b",
    sevCriticalBg: "#fceceb", sevHighBg: "#fdf3e8", sevMediumBg: "#fbf6e4",
    sevLowBg: "#eef7f1", sevUnknownBg: "#f2f2f5",
    vBetter: "#1b7f3b", vWorse: "#c1262e", vUnchanged: "#6e6e73", vInconclusive: "#5856d6",
  },
  dark: {
    // These five are SEEDS, not the colours you see. Ant Design's dark
    // algorithm desaturates whatever it is given toward the page background,
    // so a value written here comes out several shades duller - which is how a
    // primary button and `var(--brand)` came to be two different blues. They
    // are chosen by solving BACKWARDS from the intended result (#44b2ff seeds
    // the #3d9adc that actually paints), and resolvePalette in antd.ts is what
    // guarantees the stylesheet is told the same answer.
    //
    // Worth knowing before reaching for a brighter one: the dark algorithm caps
    // every channel at 0xdc, so Apple's own #0a84ff / #ff453a / #ff9f0a cannot
    // be painted at all. These are the nearest reachable shades, and the blue
    // is deliberately a step lighter than the exact match so it clears 4.5:1
    // on the canvas.
    brand: "#44b2ff", brandStrong: "#66c6ff", brandSoft: "rgba(61, 154, 220, 0.18)",
    brandBorder: "rgba(61, 154, 220, 0.45)", secondary: "#a5a3ff",
    navBg: "rgba(28, 28, 30, 0.72)", navBgHover: "rgba(255, 255, 255, 0.07)",
    navBgActive: "#0071e3",
    navFg: "#a1a1a6", navFgStrong: "#f5f5f7", navFgActive: "#ffffff",
    navBorder: "rgba(255, 255, 255, 0.09)",
    canvas: "#1c1c1e", surface: "#242427", surface2: "#2c2c2f",
    border: "#38383b", borderStrong: "#4a4a4e", illSurface: "#2c2c2f",
    text: "#f5f5f7", text2: "#a1a1a6", text3: "#6e6e73",
    markBg: "rgba(255, 212, 38, 0.16)", markBd: "rgba(255, 212, 38, 0.42)",
    ok: "#35f264", okBg: "rgba(48, 209, 88, 0.16)", okBd: "rgba(48, 209, 88, 0.42)",
    pending: "#ffb708", pendingBg: "rgba(220, 159, 10, 0.16)", pendingBd: "rgba(220, 159, 10, 0.42)",
    review: "#44b2ff", reviewBg: "rgba(61, 154, 220, 0.16)", reviewBd: "rgba(61, 154, 220, 0.42)",
    danger: "#ff4e41", dangerBg: "rgba(220, 69, 58, 0.16)", dangerBd: "rgba(220, 69, 58, 0.42)",
    base: "#a5a3ff", baseBg: "rgba(120, 118, 235, 0.18)", baseBd: "rgba(120, 118, 235, 0.45)",
    inherit: "#a1a1a6", inheritBg: "rgba(161, 161, 166, 0.14)", inheritBd: "rgba(161, 161, 166, 0.32)",
    sevCritical: "#ff6961", sevHigh: "#ff9f0a", sevMedium: "#e0b93a",
    sevLow: "#30d158", sevUnknown: "#98989d",
    sevCriticalBg: "rgba(255, 105, 97, 0.18)", sevHighBg: "rgba(255, 159, 10, 0.18)",
    sevMediumBg: "rgba(224, 185, 58, 0.18)", sevLowBg: "rgba(48, 209, 88, 0.18)",
    sevUnknownBg: "rgba(152, 152, 157, 0.18)",
    vBetter: "#30d158", vWorse: "#ff6961", vUnchanged: "#98989d", vInconclusive: "#a5a3ff",
  },
  // Environment identity, on the system palette too - but these stay the same
  // in both modes on purpose: an environment does not change identity when the
  // lights go out.
  envColors: {
    production: "#5856d6", prod: "#5856d6", staging: "#c25e00", development: "#1b7f3b",
    lab: "#0f9d8f", sandbox: "#9f4bd0", nonprod: "#007c91",
  },
};

// -----------------------------------------------------------------------------
// PRESETS. A preset is a named look built on top of the defaults. Ship several;
// an operator picks ONE with a single line below, and BOTH tools follow, which
// is the whole point of this folder being identical in each of them.
//
//  - "default"    the system palette on a translucent chrome: what both tools
//                 ship, and what the rest of this file is written around.
//  - "graphite"   the same shapes with the colour taken out of the chrome: a
//                 near-neutral accent for a deployment that wants the data to
//                 be the only saturated thing on screen. (Its flatter elevation
//                 lives in tokens.css under :root[data-preset="graphite"].)
//  - "gateway"    the cyan corporate mark, for a deployment that must wear it.
//
// A preset never brings back the opaque navy chrome: the navigation is a
// material in every one of them, because that is a fact about the design
// system rather than a colour choice. What a preset changes is the ACCENT and
// the temperature of the neutrals.
// -----------------------------------------------------------------------------
export const presets: Record<string, DeepPartial<ThemeTokens>> = {
  default: {},
  graphite: {
    shape: { borderRadius: 8 },
    light: {
      brand: "#3a3a3c", brandStrong: "#1d1d1f", brandSoft: "#eeeef0", brandBorder: "#cfcfd4",
      secondary: "#0071e3",
      navBg: "rgba(242, 242, 245, 0.74)", navBgActive: "#3a3a3c",
      canvas: "#ededf0", surface: "#ffffff", surface2: "#f4f4f6",
      border: "#e2e2e5", borderStrong: "#cfcfd4",
      review: "#3a3a3c", reviewBg: "#eeeef0", reviewBd: "#cfcfd4",
    },
    dark: {
      brand: "#d8d8dc", brandStrong: "#ececf0", brandSoft: "rgba(200, 200, 208, 0.16)",
      brandBorder: "rgba(200, 200, 208, 0.4)", secondary: "#44b2ff",
      navBg: "rgba(24, 24, 26, 0.74)", navBgActive: "#5a5a5f",
      canvas: "#161618", surface: "#1f1f22", surface2: "#28282b",
      border: "#333336", borderStrong: "#454549",
      review: "#d8d8dc", reviewBg: "rgba(200, 200, 208, 0.14)",
      reviewBd: "rgba(200, 200, 208, 0.36)",
    },
  },
  gateway: {
    light: {
      brand: "#007ba8", brandStrong: "#00607f", brandSoft: "#e3f4fb", brandBorder: "#a9d9ec",
      secondary: "#00607f",
      navBg: "rgba(240, 246, 249, 0.74)", navBgActive: "#007ba8",
      review: "#007ba8", reviewBg: "#e3f4fb", reviewBd: "#a9d9ec",
    },
    dark: {
      brand: "#45b8e3", brandStrong: "#6ac9ea", brandSoft: "rgba(0, 159, 219, 0.16)",
      brandBorder: "rgba(0, 159, 219, 0.45)", secondary: "#6ac9ea",
      navBg: "rgba(20, 28, 34, 0.74)", navBgActive: "#0084b8",
      review: "#45b8e3", reviewBg: "rgba(0, 159, 219, 0.14)", reviewBd: "rgba(0, 159, 219, 0.4)",
    },
  },
};

// THE SWITCH. Change this one value and every tool that shares this folder
// changes with it. Leave it "default" to ship unchanged.
export const ACTIVE_PRESET = "default";

// -----------------------------------------------------------------------------
// LOCAL OVERRIDES. Deep-merged over the active preset. Whatever you put here
// applies to THIS repository only, so anything in it is a deliberate decision
// to let the two tools differ. Keep it empty unless you mean that.
// -----------------------------------------------------------------------------
export const tokenOverrides: DeepPartial<ThemeTokens> = {};

// --- machinery (usually no need to touch below) ------------------------------

export type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];
};

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function deepMerge<T>(base: T, over: DeepPartial<T>): T {
  if (!isObject(base) || !isObject(over)) return (over as T) ?? base;
  const out: Record<string, unknown> = { ...(base as Record<string, unknown>) };
  for (const [k, v] of Object.entries(over)) {
    const b = (base as Record<string, unknown>)[k];
    out[k] = isObject(b) && isObject(v) ? deepMerge(b, v as DeepPartial<unknown>) : v;
  }
  return out as T;
}

export { deepMerge };

/** The resolved, active tokens: defaults, then the chosen preset, then any
 *  local overrides on top. */
export const tokens: ThemeTokens = deepMerge(
  deepMerge(defaultTokens, presets[ACTIVE_PRESET] ?? {}),
  tokenOverrides,
);

/** One mode's palette as `--var: value;` declarations. */
function paletteToCss(p: Palette): string {
  return VAR_MAP.map(([key, cssVar]) => `${cssVar}: ${p[key]};`).join(" ");
}

/** The colour layer, as a stylesheet.
 *
 *  `resolve` is how the two halves are kept honest: the caller (the Vite
 *  plugin) hands in `resolvePalette` from antd.ts, which asks the component
 *  library what it is actually going to paint. Without it the stylesheet would
 *  state the SEED colours and the components would paint the shades Ant
 *  derives from them, and in dark mode those are visibly different.
 *
 *  The DEFAULT palette lands on :root; every OTHER preset is emitted scoped to
 *  :root[data-preset="<name>"], so switching preset (the attribute the brand
 *  plugin stamps on <html> at parse time) flips the whole palette with no
 *  rebuild, and every look always ships together. Local overrides apply on top
 *  of whichever preset is active. */
export function renderRootCss(resolve?: (p: Palette, dark: boolean) => Palette): string {
  const r = resolve ?? ((p: Palette) => p);
  const base = deepMerge(defaultTokens, tokenOverrides);
  const blocks = [
    `:root { ${paletteToCss(r(base.light, false))} }`,
    `[data-theme="dark"] { ${paletteToCss(r(base.dark, true))} }`,
  ];
  for (const [name, over] of Object.entries(presets)) {
    if (name === "default" || !over) continue;
    const merged = deepMerge(deepMerge(defaultTokens, over), tokenOverrides);
    blocks.push(`:root[data-preset="${name}"] { ${paletteToCss(r(merged.light, false))} }`);
    blocks.push(
      `[data-theme="dark"][data-preset="${name}"] { ${paletteToCss(r(merged.dark, true))} }`,
    );
  }
  return blocks.join("\n");
}
