// =============================================================================
// THE SHARED DESIGN TOKENS. One palette, two products.
// =============================================================================
// This file is part of `uikit/`, which is BYTE-IDENTICAL in every tool that
// uses it (see README.md). Nothing app-specific belongs here: a product's name,
// mark and favicon live in its own `src/brand.ts`, outside this folder, which
// is why the folder can be copied wholesale between repositories.
//
// One config drives three layers so they cannot drift apart:
//   1. CSS custom properties (:root / [data-theme="dark"]) - generated by
//      renderRootCss() and inlined into <head> by vitePluginBrand.ts, so there
//      is no flash of the wrong theme.
//   2. Ant Design tokens - antd.ts reads this file instead of hardcoding.
//   3. The uikit's own stylesheets and primitives, which name only variables.
//
// Keep this file dependency-free: it is imported by both the browser bundle and
// the Node-side Vite plugin.
// -----------------------------------------------------------------------------

/** A full set of themeable colors for one mode (light or dark). */
export interface Palette {
  // Primary (brand) and its variants
  brand: string;
  brandStrong: string; // hover / pressed brand
  brandSoft: string; // tinted fill behind selected/brand surfaces
  brandBorder: string;
  // Secondary accent. Defaults to brandStrong so it is inert until you set it;
  // exposed as var(--secondary) for your own accents.
  secondary: string;
  // Sidebar / navigation rail
  navBg: string;
  navBgHover: string;
  navBgActive: string;
  navFg: string;
  navFgActive: string;
  navBorder: string;
  // Surfaces: canvas (page) < surface (content) < surface2 (raised or sunken
  // well - the same value serves both, because a recessed panel and a raised
  // one differ by their shadow, not by their fill)
  canvas: string;
  surface: string;
  surface2: string;
  border: string;
  borderStrong: string;
  illSurface: string; // "paper" fill inside the state illustrations
  // Text
  text: string;
  text2: string;
  text3: string;
  // Semantic status triples (foreground / pastel background / border)
  ok: string; okBg: string; okBd: string;
  pending: string; pendingBg: string; pendingBd: string;
  review: string; reviewBg: string; reviewBd: string;
  danger: string; dangerBg: string; dangerBd: string;
  // The "you are here" wash: a highlighter over the thing a link led to. It is
  // not a status - nothing is wrong or pending about a value somebody asked to
  // be shown - so it gets its own colour rather than borrowing one that means
  // something.
  markBg: string; markBd: string;
  // Provenance (base = inherited from a shared layer, inherit = neutral)
  base: string; baseBg: string; baseBd: string;
  inherit: string; inheritBg: string; inheritBd: string;
  // Severity, and the surface each severity dot sits on. A FIVE-step scale
  // rather than the four semantic tones, because "unknown" is a real answer
  // that must not read as "none": a package nobody has scanned is not a clean
  // one. COLOUR IS NEVER THE ONLY SIGNAL - every severity is also a word and a
  // dot whose fill differs - so these survive greyscale and colour blindness.
  sevCritical: string; sevHigh: string; sevMedium: string; sevLow: string; sevUnknown: string;
  sevCriticalBg: string; sevHighBg: string; sevMediumBg: string; sevLowBg: string; sevUnknownBg: string;
  // The verdict of a comparison. `inconclusive` is deliberately not a grey that
  // reads as "nothing happened": it is a state with an action in it (go and
  // look at the rest), and looking like an empty result is how it gets ignored.
  vBetter: string; vWorse: string; vUnchanged: string; vInconclusive: string;
}

/** The palette-and-metrics half of a theme. Identity lives in brand.ts. */
export interface ThemeTokens {
  /** Shape tokens fed to Ant Design. */
  shape: { borderRadius: number; controlHeight: number };
  /** Type tokens fed to Ant Design. */
  type: { fontFamily: string; monoFamily: string; fontSizeBase: number };
  light: Palette;
  dark: Palette;
  /** Environment identity colors (which environment an instance runs in). */
  envColors: Record<string, string>;
}

// Palette key -> CSS custom property. Every stylesheet and every primitive in
// this kit names one of these and never a hex, which is what makes a rebrand
// one edit instead of a search.
export const VAR_MAP: Array<[keyof Palette, string]> = [
  ["brand", "--brand"], ["brandStrong", "--brand-strong"], ["brandSoft", "--brand-soft"],
  ["brandBorder", "--brand-border"], ["secondary", "--secondary"],
  ["navBg", "--nav-bg"], ["navBgHover", "--nav-bg-hover"], ["navBgActive", "--nav-bg-active"],
  ["navFg", "--nav-fg"], ["navFgActive", "--nav-fg-active"], ["navBorder", "--nav-border"],
  ["canvas", "--canvas"], ["surface", "--surface"], ["surface2", "--surface-2"],
  ["border", "--border"], ["borderStrong", "--border-strong"], ["illSurface", "--ill-surface"],
  ["text", "--text"], ["text2", "--text-2"], ["text3", "--text-3"],
  ["ok", "--c-ok"], ["okBg", "--c-ok-bg"], ["okBd", "--c-ok-bd"],
  ["pending", "--c-pending"], ["pendingBg", "--c-pending-bg"], ["pendingBd", "--c-pending-bd"],
  ["review", "--c-review"], ["reviewBg", "--c-review-bg"], ["reviewBd", "--c-review-bd"],
  ["danger", "--c-danger"], ["dangerBg", "--c-danger-bg"], ["dangerBd", "--c-danger-bd"],
  ["markBg", "--c-mark-bg"], ["markBd", "--c-mark-bd"],
  ["base", "--c-base"], ["baseBg", "--c-base-bg"], ["baseBd", "--c-base-bd"],
  ["inherit", "--c-inherit"], ["inheritBg", "--c-inherit-bg"], ["inheritBd", "--c-inherit-bd"],
  ["sevCritical", "--sev-critical"], ["sevHigh", "--sev-high"], ["sevMedium", "--sev-medium"],
  ["sevLow", "--sev-low"], ["sevUnknown", "--sev-unknown"],
  ["sevCriticalBg", "--sev-critical-bg"], ["sevHighBg", "--sev-high-bg"],
  ["sevMediumBg", "--sev-medium-bg"], ["sevLowBg", "--sev-low-bg"],
  ["sevUnknownBg", "--sev-unknown-bg"],
  ["vBetter", "--v-better"], ["vWorse", "--v-worse"], ["vUnchanged", "--v-unchanged"],
  ["vInconclusive", "--v-inconclusive"],
];

// -----------------------------------------------------------------------------
// Defaults: the identity these tools ship with. Change values via a PRESET
// below rather than editing these, so the baseline is always there to diff
// against - and so both products move together when one of them moves.
// -----------------------------------------------------------------------------
export const defaultTokens: ThemeTokens = {
  shape: { borderRadius: 6, controlHeight: 30 },
  type: {
    fontFamily:
      `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif`,
    monoFamily:
      `"JetBrains Mono", ui-monospace, "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace`,
    fontSizeBase: 13,
  },
  light: {
    brand: "#0057b8", brandStrong: "#004494", brandSoft: "#e8f1fb", brandBorder: "#b2ccea",
    secondary: "#004494",
    navBg: "#0a1f3c", navBgHover: "rgba(255, 255, 255, 0.06)", navBgActive: "#0f62d6",
    navFg: "#b9c6d8", navFgActive: "#ffffff", navBorder: "rgba(255, 255, 255, 0.08)",
    canvas: "#eef1f6", surface: "#ffffff", surface2: "#f7f9fc",
    border: "#e7ebf1", borderStrong: "#d5dbe4", illSurface: "#ffffff",
    text: "#101828", text2: "#475467", text3: "#98a2b3",
    markBg: "#fdf3c8", markBd: "#f0d264",
    ok: "#067647", okBg: "#e2f6ea", okBd: "#b7e6cb",
    pending: "#b54708", pendingBg: "#fcf1dd", pendingBd: "#f4dda4",
    review: "#0057b8", reviewBg: "#e4eefa", reviewBd: "#bdd4ee",
    danger: "#b42318", dangerBg: "#fcebe9", dangerBd: "#f5c8c2",
    base: "#6941c6", baseBg: "#f4f0fd", baseBd: "#e0d3fa",
    inherit: "#667085", inheritBg: "#f2f4f7", inheritBd: "#e0e4ea",
    sevCritical: "#b4232b", sevHigh: "#d9660b", sevMedium: "#b98900",
    sevLow: "#2e7d4f", sevUnknown: "#7a8694",
    sevCriticalBg: "#fbeded", sevHighBg: "#fdf2e8", sevMediumBg: "#fcf7e6",
    sevLowBg: "#eff6f1", sevUnknownBg: "#f1f3f5",
    vBetter: "#1f7a3d", vWorse: "#b4232b", vUnchanged: "#5a6675", vInconclusive: "#7a4fbf",
  },
  dark: {
    // These five are SEEDS, not the colours you see. Ant Design's dark
    // algorithm desaturates whatever it is given toward the page background,
    // so a value written here comes out several shades duller - which is how a
    // primary button and `var(--brand)` came to be two different blues. They
    // are chosen by solving BACKWARDS from the intended result (#58a9ff seeds
    // the #4e93dc that actually paints), and resolvePalette in antd.ts is what
    // guarantees the stylesheet is told the same answer.
    brand: "#58a9ff", brandStrong: "#74abec", brandSoft: "rgba(77, 148, 232, 0.16)",
    brandBorder: "rgba(77, 148, 232, 0.45)", secondary: "#74abec",
    navBg: "#081830", navBgHover: "rgba(255, 255, 255, 0.07)", navBgActive: "#0f62d6",
    navFg: "#a8b6ca", navFgActive: "#ffffff", navBorder: "rgba(255, 255, 255, 0.08)",
    canvas: "#101318", surface: "#171b21", surface2: "#1c2129",
    border: "#262b33", borderStrong: "#353b45", illSurface: "#232a33",
    text: "#e6e9ee", text2: "#a5adba", text3: "#6c7684",
    markBg: "rgba(250, 204, 21, 0.16)", markBd: "rgba(250, 204, 21, 0.42)",
    ok: "#58e2a0", okBg: "rgba(23, 178, 106, 0.14)", okBd: "rgba(23, 178, 106, 0.4)",
    pending: "#ffcd43", pendingBg: "rgba(247, 144, 9, 0.14)", pendingBd: "rgba(247, 144, 9, 0.4)",
    review: "#71beff", reviewBg: "rgba(77, 148, 232, 0.14)", reviewBd: "rgba(77, 148, 232, 0.4)",
    danger: "#ff827a", dangerBg: "rgba(240, 68, 56, 0.14)", dangerBd: "rgba(240, 68, 56, 0.4)",
    base: "#b490f5", baseBg: "rgba(148, 108, 230, 0.16)", baseBd: "rgba(148, 108, 230, 0.42)",
    inherit: "#98a2b3", inheritBg: "rgba(152, 162, 179, 0.14)", inheritBd: "rgba(152, 162, 179, 0.34)",
    sevCritical: "#f2726f", sevHigh: "#f0913f", sevMedium: "#e0b13a",
    sevLow: "#4cc38a", sevUnknown: "#98a2b3",
    sevCriticalBg: "rgba(180, 35, 43, 0.18)", sevHighBg: "rgba(217, 102, 11, 0.18)",
    sevMediumBg: "rgba(185, 137, 0, 0.18)", sevLowBg: "rgba(46, 125, 79, 0.18)",
    sevUnknownBg: "rgba(122, 134, 148, 0.18)",
    vBetter: "#4cc38a", vWorse: "#f2726f", vUnchanged: "#98a2b3", vInconclusive: "#b490f5",
  },
  envColors: {
    production: "#4338ca", prod: "#4338ca", staging: "#b54708", development: "#067647",
    lab: "#0f9d6e", sandbox: "#7c3aed", nonprod: "#0891b2",
  },
};

// -----------------------------------------------------------------------------
// PRESETS. A preset is a named look built on top of the defaults. Ship several;
// an operator picks ONE with a single line below, and BOTH tools follow, which
// is the whole point of this folder being identical in each of them.
//
//  - "default"    the original identity: a serious cobalt on a pastel canvas,
//                 with soft-UI elevation.
//  - "instrument" flatter and more owned: crisp elevation via CSS, a deeper
//                 canvas, hierarchy from borders and value contrast rather than
//                 a field of floating shadows. (The elevation half lives in
//                 tokens.css under :root[data-preset="instrument"].)
//  - "gateway"    the cyan corporate mark, for a deployment that must wear it.
// -----------------------------------------------------------------------------
export const presets: Record<string, DeepPartial<ThemeTokens>> = {
  default: {},
  instrument: {
    shape: { borderRadius: 7 },
    light: {
      brand: "#2f4bd6", brandStrong: "#2439ab", brandSoft: "#ecefff", brandBorder: "#c5cdf6",
      secondary: "#2f4bd6",
      navBg: "#0b1730", navBgActive: "#2f4bd6",
      canvas: "#e8e9ee", surface: "#ffffff", surface2: "#f4f5f8",
      border: "#e1e3ea", borderStrong: "#ccd0da",
      text: "#0f1729", text2: "#465063", text3: "#8b93a4",
      review: "#2f4bd6", reviewBg: "#ecefff", reviewBd: "#c5cdf6",
    },
    dark: {
      brand: "#8098f6", brandStrong: "#97abf8", brandSoft: "rgba(90,110,240,0.18)",
      brandBorder: "rgba(90,110,240,0.5)", secondary: "#8098f6",
      navBg: "#080f1f", navBgActive: "#2f4bd6",
      canvas: "#0d1017", surface: "#141821", surface2: "#1a1f2a",
      border: "#242a36", borderStrong: "#333a48",
      review: "#8098f6", reviewBg: "rgba(90,110,240,0.16)", reviewBd: "rgba(90,110,240,0.42)",
    },
  },
  gateway: {
    light: {
      brand: "#007ba8", brandStrong: "#00607f", brandSoft: "#e3f4fb", brandBorder: "#a9d9ec",
      secondary: "#00607f",
      navBg: "#0b1f3a", navBgActive: "#009fdb",
      review: "#007ba8", reviewBg: "#e3f4fb", reviewBd: "#a9d9ec",
    },
    dark: {
      brand: "#45b8e3", brandStrong: "#6ac9ea", brandSoft: "rgba(0, 159, 219, 0.16)",
      brandBorder: "rgba(0, 159, 219, 0.45)", secondary: "#6ac9ea",
      navBg: "#07182d", navBgActive: "#0084b8",
      review: "#45b8e3", reviewBg: "rgba(0, 159, 219, 0.14)", reviewBd: "rgba(0, 159, 219, 0.4)",
    },
  },
};

// THE SWITCH. Change this one value and every tool that shares this folder
// changes with it. Leave it "default" to ship unchanged.
export const ACTIVE_PRESET = "default";

// -----------------------------------------------------------------------------
// LOCAL OVERRIDES. Deep-merged over the active preset. Whatever you put here
// applies to THIS repository only, so anything in it is a deliberate decision
// to let the two tools differ. Keep it empty unless you mean that.
// -----------------------------------------------------------------------------
export const tokenOverrides: DeepPartial<ThemeTokens> = {};

// --- machinery (usually no need to touch below) ------------------------------

export type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K];
};

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function deepMerge<T>(base: T, over: DeepPartial<T>): T {
  if (!isObject(base) || !isObject(over)) return (over as T) ?? base;
  const out: Record<string, unknown> = { ...(base as Record<string, unknown>) };
  for (const [k, v] of Object.entries(over)) {
    const b = (base as Record<string, unknown>)[k];
    out[k] = isObject(b) && isObject(v) ? deepMerge(b, v as DeepPartial<unknown>) : v;
  }
  return out as T;
}

export { deepMerge };

/** The resolved, active tokens: defaults, then the chosen preset, then any
 *  local overrides on top. */
export const tokens: ThemeTokens = deepMerge(
  deepMerge(defaultTokens, presets[ACTIVE_PRESET] ?? {}),
  tokenOverrides,
);

/** One mode's palette as `--var: value;` declarations. */
function paletteToCss(p: Palette): string {
  return VAR_MAP.map(([key, cssVar]) => `${cssVar}: ${p[key]};`).join(" ");
}

/** The colour layer, as a stylesheet.
 *
 *  `resolve` is how the two halves are kept honest: the caller (the Vite
 *  plugin) hands in `resolvePalette` from antd.ts, which asks the component
 *  library what it is actually going to paint. Without it the stylesheet would
 *  state the SEED colours and the components would paint the shades Ant
 *  derives from them, and in dark mode those are visibly different.
 *
 *  The DEFAULT palette lands on :root; every OTHER preset is emitted scoped to
 *  :root[data-preset="<name>"], so switching preset (the attribute the brand
 *  plugin stamps on <html> at parse time) flips the whole palette with no
 *  rebuild, and every look always ships together. Local overrides apply on top
 *  of whichever preset is active. */
export function renderRootCss(resolve?: (p: Palette, dark: boolean) => Palette): string {
  const r = resolve ?? ((p: Palette) => p);
  const base = deepMerge(defaultTokens, tokenOverrides);
  const blocks = [
    `:root { ${paletteToCss(r(base.light, false))} }`,
    `[data-theme="dark"] { ${paletteToCss(r(base.dark, true))} }`,
  ];
  for (const [name, over] of Object.entries(presets)) {
    if (name === "default" || !over) continue;
    const merged = deepMerge(deepMerge(defaultTokens, over), tokenOverrides);
    blocks.push(`:root[data-preset="${name}"] { ${paletteToCss(r(merged.light, false))} }`);
    blocks.push(
      `[data-theme="dark"][data-preset="${name}"] { ${paletteToCss(r(merged.dark, true))} }`,
    );
  }
  return blocks.join("\n");
}
