#!/bin/sh
# Two jobs, both of which can only be done once the container knows where it
# is running: fill in nginx's resolver, and publish the SPA's runtime config.
set -eu

# --- 1. the DNS resolver ------------------------------------------------------
# nginx.conf's __DNS_RESOLVER__ is this engine's actual embedded DNS address.
# Docker's is always 127.0.0.11; Podman's (aardvark-dns) is the network's own
# gateway, a different IP per network, so it is read from /etc/resolv.conf
# rather than assumed.
RESOLVER=$(awk '/^nameserver/ { print $2; exit }' /etc/resolv.conf)
RESOLVER=${RESOLVER:-127.0.0.11}
sed -i "s/__DNS_RESOLVER__/$RESOLVER/" /etc/nginx/conf.d/app.conf

# --- 2. the SPA's runtime configuration ---------------------------------------
# Where to send the browser to sign in, and as which OIDC client.
#
# Neither value can be a build-time constant. The issuer varies per deployment,
# and the client id is GENERATED by ZITADEL when the seeder registers the
# application - so it is not knowable until the stack has been seeded, which
# happens long after this image was built. The seeder writes it to a shared
# volume (deploy/zitadel/bootstrap.mjs step 6) and this renders it into a file
# the SPA fetches.
#
# Environment wins over the file, so a deployment that provisions its identity
# provider some other way and never runs our seeder just sets both variables.
# Public values only: a public OIDC client has no secret, which is why this is
# a world-readable file served to every browser rather than a mounted secret.
SHARED=${OIDC_CONFIG_FILE:-/oidc/web.json}
OUT=/usr/share/nginx/html/runtime-config.json

field() {
  # The one field named, out of a flat JSON object. Enough for a file this
  # container writes nothing to and the seeder emits three keys into; a JSON
  # parser is not worth an added dependency in an nginx image.
  [ -f "$SHARED" ] || return 0
  sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$SHARED" | head -1
}

ISSUER=${OIDC_ISSUER:-}
CLIENT_ID=${OIDC_CLIENT_ID:-}
REDIRECT_URI=${OIDC_REDIRECT_URI:-}
[ -n "$ISSUER" ]       || ISSUER=$(field issuer)
[ -n "$CLIENT_ID" ]    || CLIENT_ID=$(field clientId)
[ -n "$REDIRECT_URI" ] || REDIRECT_URI=$(field redirectUri)

cat > "$OUT" <<JSON
{
  "oidc": {
    "issuer": "$ISSUER",
    "clientId": "$CLIENT_ID",
    "redirectUri": "$REDIRECT_URI"
  }
}
JSON

# Said once, at start, where an operator looking for "why can nobody sign in"
# will find it. Never the values themselves beyond the issuer: this line is
# about whether the wiring happened, and the file above is the wiring.
if [ -n "$CLIENT_ID" ]; then
  echo "sign-in configured: $ISSUER"
else
  echo "sign-in NOT configured: no OIDC client id in $SHARED and none in OIDC_CLIENT_ID."
  echo "  The UI will load, and will not be able to authenticate anyone."
fi

exec nginx -g 'daemon off;'
