apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  mount: kv
  type: kv-v2
  path: softwaregateway/lab/flux-notifications
  refreshAfter: 1h
  vaultAuthRef: vault-auth
  destination:
    name: flux-notifications
    create: true
