apiVersion: v1
kind: Namespace
metadata:
  name: swgw
  labels:
    app.kubernetes.io/part-of: software-gateway
    softwaregateway.io/instance: prod
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
